services:
  app:
    build: ./app
    depends_on:
      - postgres
      - ollama
    environment:
      DATABASE_URL: postgresql://cars:fs2da@postgres:5432/cardb
      OLLAMA_URL: http://ollama:11434

  scraper:
    build: ./scraper
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://cars:fs2da@postgres:5432/cardb
    mem_limit: 3g
    memswap_limit: 3g
    cpus: 4
    pids_limit: 100

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: cars
      POSTGRES_PASSWORD: fs2da
      POSTGRES_DB: cardb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      ["5433:5432"]
  
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
