[project]
name = "car-pipeline-scraper"
version = "1.0.0"
dependencies = [
   "psycopg[binary]",
   "playwright",
   "bs4",
   "lxml"
]
requires-python = ">=3.12.3"
authors = [
   {name = "Saul Torres Camas", email = "camas17st@outlook.com"}
]
description = "This is the scraper pipeline's worker."

[tool.setuptools]
py-modules = ["scraping", "scraper"]